{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
{{- if not .Values.myField.myBoolean }}
myString:
{{- .Values.myField.myString | nindent 2}}
{{- else }}
myValues:
{{- with .Values.myField.myarray }}
{{- toYaml .  | nindent 2}}
{{- end }}
{{- end }}

metadata:
  name: {{ include "first-chart.serviceAccountName" . }}
  labels:
    {{- include "first-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}